name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

# TODO generate-stackbrew-library + proper matrix

jobs:
  test:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for dir in */; do
            docker build --pull "$dir"
          done
